#Change me to use the maven properties
main: org.mineacademy.punishcontrol.spigot.PunishControl
version: ${project.version}
name: PunishControl
author: ${author}

api-version: 1.13
softdepend:
  - Essentials
  - UltraPunishments