main: org.mineacademy.punishcontrol.spigot.PunishControl
version: ${project.version}
name: PunishControl
author: ${author}

api-version: 1.13
softdepend:
  - Essentials
  - LiteBans # To probably import punishments

commands:
# The command are built at runtime so you can change them easily within the settings.