# !-------------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ChatControl PRO
# !-------------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/kangarko/ChatControl-Pro/wiki
#
# !-------------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character. See
#       - http://minecraftwiki.net/wiki/Formatting_codes
#       [!] When you use them, omit the message with " " or ' '.
#
#    2) TO HIDE a message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
#
#    4) JSON is supported. For usage, see:
#       - https://github.com/kangarko/ChatControl-Pro/wiki/JSON
#
#    5) SOUND NAMES had changed as per Minecraft 1.9, compare:
#       - 1.9 and newer: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#       - 1.8 and older: https://goo.gl/ArzbZA
#
#    PS: The information above applies for all files within the ChatControl folder.
#
#    !! Messages (e.g. 'Please wait 2 seconds [...]') are stored in localization, see:
#       - https://github.com/kangarko/ChatControl-Pro/wiki/Localization
#
# !-------------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Reduce impact of spamming bots
# -------------------------------------------------------------------------------------------------



Prefix: '&8&lPUNISHCONTROL &8//&7'

Locale: en

#JSON/MYSQL
Storage: JSON

Command_Aliases: [punishcontrol,phc, pun, pc]

Punishes:
  #Should punishing only be possible with an template
  OnlyTemplate: false
  Ban:
    #Should stuff be notified
    #if an punish of this type is created?
    Permission: punishcontrol.command.ban
    Enabled: true
  Mute:
    Permission: punishcontrol.command.mute
    Enabled: true
  Warn:
    Permission: punishcontrol.command.warn
    Enabled: true

Notifications:
  Punish:
    Enabled: true
    Permission: punishcontrol.notifications.punish
  Silent-Punish:
    Enabled: true
    Permission: punishcontrol.notifications.silent-punish

Groups:
  Admin:
    Priority: 0
    Permission: punishcontrol.group.admin
    #Set to -1 to disable
    Limits:
      Ban: -1
      Mute: -1
      Warn: -1
  Moderator:
    Priority: 1
    Permission: punishcontrol.group.moderator
    Limits:
      Ban: 1 year
      Mute: 1 year
      Warn: 2 year
    Supporter:
      Priority: 2
      Permission: punishcontrol.group.supporter
      Limits:
        Ban: 1 month
        Mute: 2 month
        Warn: 3 month

Advanced:
  Cache_Results: true
  API:
    #You can disable the API for security reasons
    Enabled: True


# Do not change this value, otherwise it will corrupt your plugin installation!
Version: 1
