# !-------------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of PunishControl
# !-------------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/kangarko/PunishControl/wiki
#
# !-------------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character. See
#       - http://minecraftwiki.net/wiki/Formatting_codes
#       [!] When you use them, omit the message with " " or ' '.
#
#    2) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/kangarko/ChatControl/wiki/Use-Right-Encoding
#
#    PS: The information above applies for all files within the PunishControl folder.
#
#    !! Messages (e.g. 'Please wait 2 seconds [...]') are stored in localization, see:
#       - https://github.com/kangarko/PunishControl/wiki/Localization
#
# !-------------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------
# You can change the prefix in front of chat or console messages here:
# -------------------------------------------------------------------------------------------
Prefix: '&8&lPUNISHCONTROL &8//&7'

# -------------------------------------------------------------------------------------------
# Currently available: en (English), de (German), cz Czech (with exclusive cases support (pády)(
# fr(French), nl (Dutch), pt (Portuguese), rs (Serbian), es (Spanish), sk (Slovak)
# Read https://github.com/kangarko/PunishControl/wiki/Localization for tutorial on custom localization.
# -------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------
# What commands should trigger the punishcontrol menu (separated by a comma ,)?
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------
Command_Aliases: [punishcontrol, phc, pun, pc]

# -------------------------------------------------------------------------------------------
# Change how your data is going to be stored
# Currently available: JSON/MYSQL
# -------------------------------------------------------------------------------------------
Storage: JSON

# -----------------------------------------------------------------------------------------------------
# MySQL connection allows to store same information over multiple servers.
# -----------------------------------------------------------------------------------------------------
MySQL:
  Host: ''
  Database: ''
  Port: 3306
  User: ''
  Password: ''

Punishes:
  # Should punishing plugins only be possible with a template
  OnlyTemplate: false
  Ban:
    # Should staff be notified if a punish of this type is created?
    Permission: punishcontrol.command.ban
    Enabled: true
    Apply_On_Ip: true
  Mute:
    # Commands the player should be disallowed to use
    Allowed_Commands:
      - /msg
      - /r
    Enabled: true
    Apply_On_Ip: false
  Warn:
    Enabled: true
    # Types: ACTION_BAR, TITLE, CHAT
    Message_Type: TITLE
Notifications:
  Punish:
    Enabled: true
    Permission: punishcontrol.notifications.punish
  Silent-Punish:
    Enabled: true
    Permission: punishcontrol.notifications.silent-punish

Groups:
  Admin:
    # The group with the highest priority will be p
    Priority: 0
    Permission: punishcontrol.group.admin
    # May the group override an existing punishment?
    # For example ban a already banned player again?
    Override_Punishes: true

    Template_Only: false
    # Set to -1 to disable
    Limits:
      Ban: -1
      Mute: -1
      Warn: -1
    # Templates the Group should always be able to use.
    # Even if the Limits would prohibit the usage. (For example by the duration of the punish)
    # Set to * to enable all
    Template_Bypasses: ['*']

  Moderator:
    Priority: 1
    Permission: punishcontrol.group.moderator
    Override_Punishes: false
    Template_Only: false
    Limits:
      Ban: 1 year
      Mute: 1 year
      Warn: 2 year
    Template_Bypasses: ['*']

  Supporter:
    Priority: 2
    Permission: punishcontrol.group.supporter
    Override_Punishes: false
    Template_Only: true
    Limits:
      Ban: 1 month
      Mute: 2 month
      Warn: 3 month
    Template_Bypasses: ['*']

# -----------------------------------------------------------------------------------------------------
# Advanced settings for PunishControl
# In most cases it is absolutly unnecessary to touch them.
#
# -> Don't change them unless you really know what you are doing.
# -----------------------------------------------------------------------------------------------------
Advanced:

  # Change how the date should be formatted in our menus & commands
  Date_Format: hh:mm MM/dd/yyyy

  # Set to false if your server if effectively in offline mode
  # If your server is only set to offline mode because you are using BungeeCord,
  # let this set to true.
  Online_Mode: true

  Cache_Results: true

  #
  # Only applies on spigot. If a notification will be display in the menu
  # if BungeeCord is detected and PunishControl is used on Spigot.
  #
  Encourage_Bungee_Usage: true

  #
  # Should our backup command be enabled?
  #
  Enable_Backups: true


  #
  # (Bungee-Only) Defines the latest protocol-version that our items should be compatible with
  # For a list of Protocol-Versions, please see: https://wiki.vg/Protocol_version_numbers
  # This changes how many items will be available to select in the material browsers, whic
  # for example shows up, when you want to customize ur items
  #
  Min_Protocol_Version_Supported: 47
  #
  # Define how names and other stuff should be searched for
  #
  Searcher:
    #
    # Define how similar strings need to be using the /search command
    #
    Min_Similarity_Needed: 0.85

    #
    # If our value starts with the same letters as our search-input.
    # Should we then return it as a result?
    #
    Use_Starts_With: true

# -----------------------------------------------------------------------------------------------------
# Print more informative messages about the plugin and its features?
#
# You normally don't need to edit this unless you have problems or been navigated by the dev.
# Specify sections to debug.
# -----------------------------------------------------------------------------------------------------
Debug: []

# Do not change this value, otherwise, it will corrupt your plugin installation!
Version: 2
