Prefix: '&8&lPUNISHCONTROL &8//&7'

Locale: en

#JSON/MYSQL
Storage: JSON

Command_Aliases: [punishcontrol,phc, pun, pc]

Punishes:
  #Should punishing only be possible with an template
  OnlyTemplate: false
  Ban:
    #Should stuff be notified
    #if an punish of this type is created?
    Permission: punishcontrol.command.ban
    Enabled: true
  Mute:
    Permission: punishcontrol.command.mute
    Enabled: true
  Warn:
    Permission: punishcontrol.command.warn
    Enabled: true

Notifications:
  Punish:
    Enabled: true
    Permission: punishcontrol.notifications.punish
  Silent-Punish:
    Enabled: true
    Permission: punishcontrol.notifications.silent-punish

Groups:
  Admin:
    Priority: 0
    Permission: punishcontrol.group.admin
    #Set to -1 to disable
    Limits:
      Ban: -1
      Mute: -1
      Warn: -1
  Moderator:
    Priority: 1
    Permission: punishcontrol.group.moderator
    Limits:
      Ban: 1 year
      Mute: 1 year
      Warn: 2 year
    Supporter:
      Priority: 2
      Permission: punishcontrol.group.supporter
      Limits:
        Ban: 1 month
        Mute: 2 month
        Warn: 3 month

Advanced:
  Cache_Results: true

# Do not change this value, otherwise it will corrupt your plugin installation!
Version: 1
