Prefix: '&8&lPUNISHCONTROL &8//&7'

Locale: en

#JSON/MYSQL
Storage: JSON

Command_Aliases: [punishcontrol,phc, pun, pc]

Punishes:
  Ban:
    Enabled: true
  Warn:
    Enabled: true
  Mute:
    Enabled: true

Groups:
  Admin:
    Priority: 0
    Permission: punishcontrol.groups.admin


Advanced:
  Cache_Results: true

# Do not change this value, otherwise it will corrupt your plugin installation!
Version: 1
